<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>qcar_http_odom</name>
  <version>0.1.0</version>
  <description>Polls an HTTP pose endpoint and publishes nav_msgs/Odometry on /odom_opti</description>
  <maintainer email="moizsaeed2004@gmail.com">moix-07</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
